CREATE TEMP TABLE temp_rides AS
WITH raw_rides AS (
  SELECT
    ride_id,
    ride_code,
    driver_id,
    passenger_id,
    vehicle_type_id,
    pickup_zone_id,
    dropoff_zone_id,
    pickup_address,
    dropoff_address,
    pickup_lat,
    pickup_lon,
    dropoff_lat,
    dropoff_lon,
    requested_at,
    accepted_at,
    picked_up_at,
    completed_at,
    cancelled_at,
    distance_km,
    duration_minutes,
    base_fare,
    distance_fare,
    time_fare,
    surge_multiplier,
    promo_discount,
    total_fare,
    ride_status,
    cancellation_reason,
    passenger_rating,
    driver_rating,
    notes,
    created_at,
    updated_at,
    COALESCE(_source_system, 'postgres') AS _source_system
  FROM `{{ params.project_id }}.dev_bronze_pg.rides`
),

deduplicated_rides AS (
  SELECT * EXCEPT(rn)
  FROM (
    SELECT
      *,
      ROW_NUMBER() OVER (
        PARTITION BY ride_id
        ORDER BY updated_at DESC, created_at DESC, requested_at DESC
      ) AS rn
    FROM raw_rides
  )
  WHERE rn = 1
)

SELECT
  ride_id,
  ride_code,
  driver_id,
  passenger_id,
  vehicle_type_id,
  pickup_zone_id,
  dropoff_zone_id,
  pickup_address,
  dropoff_address,
  pickup_lat,
  pickup_lon,
  dropoff_lat,
  dropoff_lon,
  requested_at,
  accepted_at,
  picked_up_at,
  completed_at,
  cancelled_at,
  distance_km,
  duration_minutes,
  base_fare,
  distance_fare,
  time_fare,
  surge_multiplier,
  promo_discount,
  total_fare,
  ride_status,
  cancellation_reason,
  passenger_rating,
  driver_rating,
  notes,
  created_at,
  updated_at,
  _source_system,
  CURRENT_TIMESTAMP() AS _ingested_at
FROM deduplicated_rides;

MERGE INTO `{{ params.project_id }}.dev_label.rides` T
USING temp_rides S
ON T.ride_id = S.ride_id

WHEN MATCHED THEN
  UPDATE SET
    T.ride_code = S.ride_code,
    T.driver_id = S.driver_id,
    T.passenger_id = S.passenger_id,
    T.vehicle_type_id = S.vehicle_type_id,
    T.pickup_zone_id = S.pickup_zone_id,
    T.dropoff_zone_id = S.dropoff_zone_id,
    T.pickup_address = S.pickup_address,
    T.dropoff_address = S.dropoff_address,
    T.pickup_lat = S.pickup_lat,
    T.pickup_lon = S.pickup_lon,
    T.dropoff_lat = S.dropoff_lat,
    T.dropoff_lon = S.dropoff_lon,
    T.requested_at = S.requested_at,
    T.accepted_at = S.accepted_at,
    T.picked_up_at = S.picked_up_at,
    T.completed_at = S.completed_at,
    T.cancelled_at = S.cancelled_at,
    T.distance_km = S.distance_km,
    T.duration_minutes = S.duration_minutes,
    T.base_fare = S.base_fare,
    T.distance_fare = S.distance_fare,
    T.time_fare = S.time_fare,
    T.surge_multiplier = S.surge_multiplier,
    T.promo_discount = S.promo_discount,
    T.total_fare = S.total_fare,
    T.ride_status = S.ride_status,
    T.cancellation_reason = S.cancellation_reason,
    T.passenger_rating = S.passenger_rating,
    T.driver_rating = S.driver_rating,
    T.notes = S.notes,
    T.created_at = S.created_at,
    T.updated_at = S.updated_at,
    T._source_system = S._source_system,
    T._ingested_at = S._ingested_at

WHEN NOT MATCHED THEN
  INSERT (
    ride_id,
    ride_code,
    driver_id,
    passenger_id,
    vehicle_type_id,
    pickup_zone_id,
    dropoff_zone_id,
    pickup_address,
    dropoff_address,
    pickup_lat,
    pickup_lon,
    dropoff_lat,
    dropoff_lon,
    requested_at,
    accepted_at,
    picked_up_at,
    completed_at,
    cancelled_at,
    distance_km,
    duration_minutes,
    base_fare,
    distance_fare,
    time_fare,
    surge_multiplier,
    promo_discount,
    total_fare,
    ride_status,
    cancellation_reason,
    passenger_rating,
    driver_rating,
    notes,
    created_at,
    updated_at,
    _source_system,
    _ingested_at
  )
  VALUES (
    S.ride_id,
    S.ride_code,
    S.driver_id,
    S.passenger_id,
    S.vehicle_type_id,
    S.pickup_zone_id,
    S.dropoff_zone_id,
    S.pickup_address,
    S.dropoff_address,
    S.pickup_lat,
    S.pickup_lon,
    S.dropoff_lat,
    S.dropoff_lon,
    S.requested_at,
    S.accepted_at,
    S.picked_up_at,
    S.completed_at,
    S.cancelled_at,
    S.distance_km,
    S.duration_minutes,
    S.base_fare,
    S.distance_fare,
    S.time_fare,
    S.surge_multiplier,
    S.promo_discount,
    S.total_fare,
    S.ride_status,
    S.cancellation_reason,
    S.passenger_rating,
    S.driver_rating,
    S.notes,
    S.created_at,
    S.updated_at,
    S._source_system,
    S._ingested_at
  );