connector.name=mysql
connection-url=jdbc:mysql://${ENV:MYSQL_HOST}:3306?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Jakarta
connection-user=${ENV:MYSQL_USER}
connection-password=${ENV:MYSQL_PASSWORD}

