connector.name=mysql
# if use network_mode: host, use port 3307
connection-url=jdbc:mysql://127.0.0.1:3307?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Jakarta
connection-user=${ENV:MYSQL_USER}
connection-password=${ENV:MYSQL_PASSWORD}

