connector.name=postgresql
# if use network_mode: host, use port 5433
connection-url=jdbc:postgresql://127.0.0.1:5433/ride_ops_pg
connection-user=${ENV:POSTGRES_USER}
connection-password=${ENV:POSTGRES_PASSWORD}


